#ifndef I_CURSES_INCLUDED
#define I_CURSES_INCLUDED

#define stdscr 0
#define wmove NOOP
#define waddch NOOP
#define waddnstr NOOP
#define refresh NOOP
#define wrefresh NOOP
#define LINES 24
#define wattrset 0
#define curscr 0
#define clear NOOP
#define wclear NOOP
#define COLS 80
#define winch NOOP
#define unctrl NOOP
#define clearok NOOP
#define wtouchln 0
#define wclrtoeol 0
#define raw NOOP
#define printw NOOP
#define mvwprintw NOOP
#define mvcur NOOP
#define keypad NOOP
#define delwin NOOP
#define wprintw NOOP
#define noecho NOOP
#define newwin NOOP
#define leaveok NOOP
#define nocbreak NOOP
#define mvwin NOOP
#define mvprintw NOOP
#define initscr NOOP
#define idlok NOOP
#define wgetnstr NOOP
#define wgetch 0
#define werase NOOP
#define erasechar NOOP
#define subwin NOOP
#define killchar NOOP
#define isendwin NOOP
#define halfdelay NOOP
#define flushinp NOOP
#define ESCDELAY 0
#define cur_term 0
#define baudrate NOOP
#define mvaddch NOOP
#define move NOOP
#define addch NOOP
#define standout NOOP
#define standend NOOP
#define mvinch NOOP
#define mvwinch NOOP
#define touchwin NOOP
#define A_CHARTEXT 0
#define inch NOOP
#define endwin NOOP
#define addstr NOOP
#define waddstr NOOP
#define clrtoeol NOOP
#define mvaddstr NOOP
#define getyx NOOP
#define tcgetattr NOOP
#define getgid NOOP
#define getloadavg NOOP
#define mvwaddch NOOP
#define getmaxx NOOP
#define getmaxy NOOP

#endif